// <auto-generated />
namespace DataMapper.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class t111 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(t111));
        
        string IMigrationMetadata.Id
        {
            get { return "202312051629375_t111"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
